import { AffiliateLinkBase, Currency, Region, Vacuum, VacuumMappingTechnology } from "../types";

export const mockVacuums: Vacuum[] = [
  {
    id: "roborock_s8_maxv_ultra",
    imageUrl: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "Roborock",
    model: "S8 MaxV Ultra",
    batteryLifeInMinutes: 180,
    suctionPowerInPascals: 10000,
    noiseLevelInDecibels: 65,
    mappingTechnology: VacuumMappingTechnology.Camera,
    hasMultiFloorMappingFeature: true,
    hasVirtualWallsFeature: true,
    hasMoppingFeature: true,
    hasSelfEmptyingFeature: true,
    hasAppControl: true,
    hasCarpetBoostFeature: true,
    hasManualControl: false,
    hasRemoteControl: false,
    hasSmartHomeIntegration: true,
    hasVoiceControl: true,
    hasZoneCleaningFeature: true,
    waterTankCapacityInLiters: 1,
    dustbinCapacityInLiters: 0.6,
    otherFeatures: [],
    affiliateLinks: [],
  },
  {
    id: "irobot_roomba_j9_combo_plus",
    imageUrl: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "iRobot",
    model: "j9 Combo Plus",
    batteryLifeInMinutes: 185,
    suctionPowerInPascals: 6000,
    noiseLevelInDecibels: 65,
    mappingTechnology: VacuumMappingTechnology.Camera,
    hasMultiFloorMappingFeature: true,
    hasVirtualWallsFeature: true,
    hasMoppingFeature: true,
    hasSelfEmptyingFeature: true,
    hasAppControl: true,
    hasCarpetBoostFeature: true,
    hasManualControl: false,
    hasRemoteControl: false,
    hasSmartHomeIntegration: true,
    hasVoiceControl: true,
    hasZoneCleaningFeature: true,
    waterTankCapacityInLiters: 1,
    dustbinCapacityInLiters: 0.6,
    otherFeatures: [],
    affiliateLinks: [],
  },
  {
    id: "dreame_x40",
    imageUrl: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "Dreame",
    model: "X40",
    batteryLifeInMinutes: 240,
    suctionPowerInPascals: 6000,
    noiseLevelInDecibels: 65,
    mappingTechnology: VacuumMappingTechnology.Laser,
    hasMultiFloorMappingFeature: true,
    hasVirtualWallsFeature: true,
    hasMoppingFeature: true,
    hasSelfEmptyingFeature: true,
    hasAppControl: true,
    hasCarpetBoostFeature: true,
    hasManualControl: false,
    hasRemoteControl: false,
    hasSmartHomeIntegration: true,
    hasVoiceControl: true,
    hasZoneCleaningFeature: true,
    waterTankCapacityInLiters: 1,
    dustbinCapacityInLiters: 0.6,
    otherFeatures: [],
    affiliateLinks: [],
  },
  {
    id: "eufy_x10_pro_omni",
    imageUrl: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "Eufy",
    model: "X10 Pro Omni",
    batteryLifeInMinutes: 180,
    suctionPowerInPascals: 8000,
    noiseLevelInDecibels: 65,
    mappingTechnology: VacuumMappingTechnology.Laser,
    hasMultiFloorMappingFeature: true,
    hasVirtualWallsFeature: true,
    hasMoppingFeature: true,
    hasSelfEmptyingFeature: true,
    hasAppControl: true,
    hasCarpetBoostFeature: true,
    hasManualControl: false,
    hasRemoteControl: false,
    hasSmartHomeIntegration: true,
    hasVoiceControl: true,
    hasZoneCleaningFeature: true,
    waterTankCapacityInLiters: 1,
    dustbinCapacityInLiters: 0.6,
    otherFeatures: [],
    affiliateLinks: [],
  },
  {
    id: "roborock_q5_pro",
    imageUrl: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "Roborock",
    model: "Q5 Pro",
    batteryLifeInMinutes: 220,
    suctionPowerInPascals: 5500,
    noiseLevelInDecibels: 65,
    mappingTechnology: VacuumMappingTechnology.Laser,
    hasMultiFloorMappingFeature: true,
    hasVirtualWallsFeature: true,
    hasMoppingFeature: true,
    hasSelfEmptyingFeature: false,
    hasAppControl: true,
    hasCarpetBoostFeature: true,
    hasManualControl: false,
    hasRemoteControl: false,
    hasSmartHomeIntegration: true,
    hasVoiceControl: true,
    hasZoneCleaningFeature: true,
    waterTankCapacityInLiters: 1,
    dustbinCapacityInLiters: 0.6,
    otherFeatures: [],
    affiliateLinks: [],
  },
  {
    id: "switchbot_k10_plus",
    imageUrl: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "SwitchBot",
    model: "K10 Plus",
    batteryLifeInMinutes: 180,
    suctionPowerInPascals: 4000,
    noiseLevelInDecibels: 65,
    mappingTechnology: VacuumMappingTechnology.Laser,
    hasMultiFloorMappingFeature: true,
    hasVirtualWallsFeature: true,
    hasMoppingFeature: true,
    hasSelfEmptyingFeature: true,
    hasAppControl: true,
    hasCarpetBoostFeature: true,
    hasManualControl: false,
    hasRemoteControl: false,
    hasSmartHomeIntegration: true,
    hasVoiceControl: true,
    hasZoneCleaningFeature: true,
    waterTankCapacityInLiters: 1,
    dustbinCapacityInLiters: 0.6,
    otherFeatures: [],
    affiliateLinks: [],
  },
  {
    id: "ecovacs_deebot_x2_omni",
    imageUrl: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "Ecovacs",
    model: "Deebot X2 Omni",
    batteryLifeInMinutes: 105,
    suctionPowerInPascals: 8000,
    noiseLevelInDecibels: 65,
    mappingTechnology: VacuumMappingTechnology.Laser,
    hasMultiFloorMappingFeature: true,
    hasVirtualWallsFeature: true,
    hasMoppingFeature: true,
    hasSelfEmptyingFeature: true,
    hasAppControl: true,
    hasCarpetBoostFeature: true,
    hasManualControl: false,
    hasRemoteControl: false,
    hasSmartHomeIntegration: true,
    hasVoiceControl: true,
    hasZoneCleaningFeature: true,
    waterTankCapacityInLiters: 1,
    dustbinCapacityInLiters: 0.6,
    otherFeatures: [],
    affiliateLinks: [],
  },
  {
    id: "shark_iq_robot_self_empty_xl_rv1001ae",
    imageUrl: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "Shark",
    model: "IQ Robot Self-Empty XL RV1001AE",
    batteryLifeInMinutes: 97,
    suctionPowerInPascals: 8000,
    noiseLevelInDecibels: 65,
    mappingTechnology: VacuumMappingTechnology.Laser,
    hasMultiFloorMappingFeature: true,
    hasVirtualWallsFeature: true,
    hasMoppingFeature: false,
    hasSelfEmptyingFeature: true,
    hasAppControl: true,
    hasCarpetBoostFeature: true,
    hasManualControl: false,
    hasRemoteControl: false,
    hasSmartHomeIntegration: true,
    hasVoiceControl: true,
    hasZoneCleaningFeature: true,
    waterTankCapacityInLiters: 1,
    dustbinCapacityInLiters: 0.6,
    otherFeatures: [],
    affiliateLinks: [],
  },
  {
    id: "roborock_s7_maxv_ultra",
    imageUrl: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "Roborock",
    model: "S7 MaxV Ultra",
    batteryLifeInMinutes: 160,
    suctionPowerInPascals: 5100,
    noiseLevelInDecibels: 65,
    mappingTechnology: VacuumMappingTechnology.Laser,
    hasMultiFloorMappingFeature: true,
    hasVirtualWallsFeature: true,
    hasMoppingFeature: true,
    hasSelfEmptyingFeature: true,
    hasAppControl: true,
    hasCarpetBoostFeature: true,
    hasManualControl: false,
    hasRemoteControl: false,
    hasSmartHomeIntegration: true,
    hasVoiceControl: true,
    hasZoneCleaningFeature: true,
    waterTankCapacityInLiters: 1,
    dustbinCapacityInLiters: 0.6,
    otherFeatures: [],
    affiliateLinks: [],
  },
];

export const mockAffiliateLinks: AffiliateLinkBase[] = [
  {
    vacuumId: "roborock_s8_maxv_ultra",
    region: Region.America,
    currency: Currency.USD,
    price: 1799.99,
    site: "Amazon",
    url: "https://www.amazon.com/roborock-s8-maxv-ultra",
  },
  {
    vacuumId: "roborock_s8_maxv_ultra",
    region: Region.Europe,
    currency: Currency.EUR,
    price: 1799.99,
    site: "Amazon",
    url: "https://www.amazon.com/roborock-s8-maxv-ultra",
  },
  {
    vacuumId: "irobot_roomba_j9_combo_plus",
    region: Region.America,
    currency: Currency.USD,
    price: 999.99,
    site: "Amazon",
    url: "https://www.amazon.com/irobot-roomba-j9-combo-plus",
  },
  {
    vacuumId: "irobot_roomba_j9_combo_plus",
    region: Region.Europe,
    currency: Currency.EUR,
    price: 999.99,
    site: "Amazon",
    url: "https://www.amazon.com/irobot-roomba-j9-combo-plus",
  },
  {
    vacuumId: "dreame_x40",
    region: Region.America,
    currency: Currency.USD,
    price: 799.99,
    site: "Amazon",
    url: "https://www.amazon.com/dreame-x40",
  },
  {
    vacuumId: "dreame_x40",
    region: Region.Europe,
    currency: Currency.EUR,
    price: 799.99,
    site: "Amazon",
    url: "https://www.amazon.com/dreame-x40",
  },
  {
    vacuumId: "eufy_x10_pro_omni",
    region: Region.America,
    currency: Currency.USD,
    price: 799.99,
    site: "Amazon",
    url: "https://www.amazon.com/eufy-x10-pro-omni",
  },
  {
    vacuumId: "eufy_x10_pro_omni",
    region: Region.Europe,
    currency: Currency.EUR,
    price: 799.99,
    site: "Amazon",
    url: "https://www.amazon.com/eufy-x10-pro-omni",
  },
];
