import { Vacuum, VacuumMappingTechnology } from "../types";

export const mockVacuums: Vacuum[] = [
  {
    id: "roborock_s8_maxv_ultra",
    name: "Roborock S8 MaxV Ultra",
    image: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "Roborock",
    model: "S8 MaxV Ultra",
    price: 1799.99,
    batteryLifeMins: 180,
    suctionPowerPa: 10000,
    noiseLevelDb: 65,
    mappingTechnology: VacuumMappingTechnology.Camera,
    multiFloorMapping: true,
    virtualWalls: true,
    mopFunction: true,
    selfEmptying: true,
    appControl: true,
    petHair: true,
  },
  {
    id: "irobot_roomba_j9_combo_plus",
    name: "iRobot Roomba j9 Combo Plus",
    image: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "iRobot",
    model: "j9 Combo Plus",
    price: 999.99,
    batteryLifeMins: 185,
    suctionPowerPa: 6000,
    noiseLevelDb: 65,
    mappingTechnology: VacuumMappingTechnology.Camera,
    multiFloorMapping: true,
    virtualWalls: true,
    mopFunction: true,
    selfEmptying: true,
    appControl: true,
    petHair: true,
  },
  {
    id: "dreame_x40",
    name: "Dreame X40",
    image: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "Dreame",
    model: "X40",
    price: 799.99,
    batteryLifeMins: 240,
    suctionPowerPa: 6000,
    noiseLevelDb: 65,
    mappingTechnology: VacuumMappingTechnology.Laser,
    multiFloorMapping: true,
    virtualWalls: true,
    mopFunction: true,
    selfEmptying: true,
    appControl: true,
    petHair: true,
  },
  {
    id: "eufy_x10_pro_omni",
    name: "Eufy X10 Pro Omni",
    image: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "Eufy",
    model: "X10 Pro Omni",
    price: 799.99,
    batteryLifeMins: 180,
    suctionPowerPa: 8000,
    noiseLevelDb: 65,
    mappingTechnology: VacuumMappingTechnology.Laser,
    multiFloorMapping: true,
    virtualWalls: true,
    mopFunction: true,
    selfEmptying: true,
    appControl: true,
    petHair: true,
  },
  {
    id: "roborock_q5_pro",
    name: "Roborock Q5 Pro",
    image: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "Roborock",
    model: "Q5 Pro",
    price: 429.99,
    batteryLifeMins: 220,
    suctionPowerPa: 5500,
    noiseLevelDb: 65,
    mappingTechnology: VacuumMappingTechnology.Laser,
    multiFloorMapping: true,
    virtualWalls: true,
    mopFunction: true,
    selfEmptying: false,
    appControl: true,
    petHair: true,
  },
  {
    id: "switchbot_k10_plus",
    name: "SwitchBot K10 Plus",
    image: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "SwitchBot",
    model: "K10 Plus",
    price: 499.99,
    batteryLifeMins: 180,
    suctionPowerPa: 4000,
    noiseLevelDb: 65,
    mappingTechnology: VacuumMappingTechnology.Laser,
    multiFloorMapping: true,
    virtualWalls: true,
    mopFunction: true,
    selfEmptying: true,
    appControl: true,
    petHair: true,
  },
  {
    id: "ecovacs_deebot_x2_omni",
    name: "Ecovacs Deebot X2 Omni",
    image: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "Ecovacs",
    model: "Deebot X2 Omni",
    price: 1499.99,
    batteryLifeMins: 105,
    suctionPowerPa: 8000,
    noiseLevelDb: 65,
    mappingTechnology: VacuumMappingTechnology.Laser,
    multiFloorMapping: true,
    virtualWalls: true,
    mopFunction: true,
    selfEmptying: true,
    appControl: true,
    petHair: true,
  },
  {
    id: "shark_iq_robot_self_empty_xl_rv1001ae",
    name: "Shark IQ Robot Self-Empty XL RV1001AE",
    image: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "Shark",
    model: "IQ Robot Self-Empty XL RV1001AE",
    price: 599.99,
    batteryLifeMins: 97,
    suctionPowerPa: 8000,
    noiseLevelDb: 65,
    mappingTechnology: VacuumMappingTechnology.Laser,
    multiFloorMapping: true,
    virtualWalls: true,
    mopFunction: false,
    selfEmptying: true,
    appControl: true,
    petHair: true,
  },
  {
    id: "roborock_s7_maxv_ultra",
    name: "Roborock S7 MaxV Ultra",
    image: "https://place-hold.it/600x600.jpg&fontsize=18",
    brand: "Roborock",
    model: "S7 MaxV Ultra",
    price: 1299.99,
    batteryLifeMins: 160,
    suctionPowerPa: 5100,
    noiseLevelDb: 65,
    mappingTechnology: VacuumMappingTechnology.Laser,
    multiFloorMapping: true,
    virtualWalls: true,
    mopFunction: true,
    selfEmptying: true,
    appControl: true,
    petHair: true,
  },
];
