import { VacuumsFilters } from "../types";

export const initialSearchFiltersState: VacuumsFilters = {
  budget: 1_000,
  numPets: 0,
  region: "americas",
  currency: "usd",
  brand: "",
  mappingTechnology: "laser" as const,
  batteryLifeInMinutes: null,
  suctionPowerInPascals: null,
  noiseLevelInDecibels: null,
  waterTankCapacityInLiters: null,
  dustbinCapacityInLiters: null,
  hasChildLockFeature: null,
  hasMoppingFeature: null,
  hasSelfEmptyingFeature: null,
  hasSelfCleaningFeature: null,
  hasZoneCleaningFeature: null,
  hasMultiFloorMappingFeature: null,
  hasVirtualWallsFeature: null,
  hasAppControlFeature: null,
  hasVoiceControlFeature: null,
  hasManualControlFeature: null,
  hasAutoLiftMopFeature: null,
  hasGoogleOrAlexaIntegrationFeature: null,
  maxObjectClearanceInMillimeters: 0,
  surfaceRecommendations: [],
};

export const FILTER_KEY_TYPE_MAPPING: Record<keyof VacuumsFilters, "number" | "string" | "boolean" | "null"> = {
  budget: "number",
  numPets: "number",
  region: "string",
  currency: "string",
  brand: "string",
  model: "string",
  mappingTechnology: "string",
  batteryLifeInMinutes: "number",
  suctionPowerInPascals: "number",
  noiseLevelInDecibels: "number",
  waterTankCapacityInLiters: "number",
  dustbinCapacityInLiters: "number",
  hasChildLockFeature: "boolean",
  hasMoppingFeature: "boolean",
  hasSelfEmptyingFeature: "boolean",
  hasSelfCleaningFeature: "boolean",
  hasZoneCleaningFeature: "boolean",
  hasMultiFloorMappingFeature: "boolean",
  hasVirtualWallsFeature: "boolean",
  hasAppControlFeature: "boolean",
  hasVoiceControlFeature: "boolean",
  hasManualControlFeature: "boolean",
  hasAutoLiftMopFeature: "boolean",
  hasGoogleOrAlexaIntegrationFeature: "boolean",
  maxObjectClearanceInMillimeters: "number",
  surfaceRecommendations: "string",
};
